apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dwk-material-ingress
spec:
  rules:
  - http:
      paths:
      - path: / # 1.8
        pathType: Prefix
        backend:
          service:
            name: theproject-svc
            port:
              number: 2345
