apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: img-claim
  namespace: project
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi