apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: project
data:
    SECRET: ENC[AES256_GCM,data:DBsR1J92bend0k5PFcboYqnEcpoD78qkQpzQaA==,iv:8GjCfjRML4vPe0V8fX72SC+pxFg9PlTSB2d+mSgeeMc=,tag:PufVn7Aaoj1NoTUopluMAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pt0kjxqmnvaahq6rlj8wq3gczzmwvty5j8lzuxm7vv9jp75ha34qs8u9a3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQTB1WTRjcExrNm1QTHJi
            MEk2QzRsbUx0VUtpbHVXWUN5Y01BUHJLNjBVCjJ4YytTNzUwQkNvc0RiajRTbDdx
            SW1GbDgvNzZJeDYxc0V3THBzcnlWdlUKLS0tICtza3FGdmY0RDdVa1d6M29HcFNj
            VTlJamhRSnVqYlAwcmM5cFU2c1UvZlkKn+kud/z9sytVdHySt0QYuE8AI7puSdJi
            yyVm7abrWwQpY8qgP/0hHny49gHic1vX4YrYDQrwnduYtLljwmoDMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-29T09:50:07Z"
    mac: ENC[AES256_GCM,data:uThv3W1MXbmV1kJpdb2HaZQJ7OMpOXSUnmeTSWy/VAcGHd34b6LP+nurT12kJ1Xuf2a2NZ127KHEUSr+ltvqcKEubcJpf3duSWR4JH5679leOiXHSfz52AftWkeEZ/m8wb5uFFe6rt0Dzl8niDwTHc7tlHckPd8U+jv+eVy0zsA=,iv:8GgjLgVFduan3N854XxWOhHoAu9CjMN6V/GhMCE2Z6U=,tag:qG/9XkuZybvdvkSNGqAXLw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
