apiVersion: v1
kind: Service
metadata:
  name: theproject-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: theproject-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8081