apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
spec:
  type: ClusterIP
  selector:
    app: pingpong-app
  ports:
    - port: 2347
      protocol: TCP
      targetPort: 2347

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres-db
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: postgres-db