apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap.yaml
  - manifests/cronjob.yaml
  - manifests/deployment.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml
  - manifests/statefulset.yaml
  - manifests/service.yaml
  - manifests/persistentvolumeclaim.yaml
images:
  - name: PROJECT/IMAGE
    newName: gcr.io/dwk-submissions/project:latest


