apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput-app
  template:
    metadata:
      labels:
        app: logoutput-app
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: log-ping-claim
      containers:
        - name: logoutput-writer
          image: gcr.io/dwk-submissions/logoutput-writer:latest
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/src/app/files
        - name: logoutput-reader
          image: gcr.io/dwk-submissions/logoutput-reader:latest
          env:
            - name: FILE_CONTENT
              valueFrom:
                configMapKeyRef:
                  name: log-pingpong-configmap
                  key: information.txt
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-pingpong-configmap
                  key: message
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/src/app/files