apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-ping-claim
  namespace: exercises
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi